### ISSUE TITLE
Simplification of the data model

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#330]
_needs better specification_

**This is the the main story for the 2.0 release**

Possibilities:
- leave out an entire table
- leave out an attribute
- aggregate attributes (eg. Shops)
- filter features by attributes
- aggregate geometries
- simplify geometries (generalize, eg streets, administrative areas, ...)
- "Object" conversion (aggragation, eg. Trees -> Forest)

The exported data should be available with simplified data, i.e. leaving out some tables.
The corresponding styles for the QGis need adaptations as well, i.e. the left out tables need to be removed from the style. It is a difference between an empty table and non-extisting data, AFAIK QGis will not be able to load the data in the latter case.

In the simplification, city limits instead of houses and similar should be happening as well.

Depends on #334 

## Ideas

* Create an so-called _pro-mode_: let user choose in various details what to leave out/take in

## Todos

- [ ] enable use of different output *trim levels*
- [ ] implement first (and only?) trim level
    - [ ] leave out table, only include
       - adminarea_a, boundary_l, geoname_l, geoname_p, landuse_a, military_a, military_p, misc_l, natural_a, natural_p, poi_p, pow_p, railway_l, road_l, route_l, utility_p, water_a, water_p, water_l, transport_l, coastline_l, landmass_a, ocean_a
    - [ ] use different sql statements for reduced data
         - [ ] simplify road_l output data: include only:
            - [ ] `track`, `grade1`, `hihgway='track' tracktype='grade1'`
            - [ ] `junction`, `grade2`, `hihgway='track' tracktype='grade2'`
            - [ ] `roundabout`, `motorway`, `hihgway='motorway' junction='roundabout'`
            - [ ] `roundabout`, `motorway_link`, `hihgway='motorway_link' junction='roundabout'`
            - [ ] `roundabout`, `primary`, `hihgway='primary' junction='roundabout'`
            - [ ] `roundabout`, `primary_link`, `hihgway='primary_link' junction='roundabout'`
            - [ ] `unclassified`, `road`, `hihgway='{}' roundabout=*`
            - [ ] `roundabout`, `roundabout`, `hihgway=* junction='roundabout'`
            - [ ] `roundabout`, `secondary`, `hihgway='secondary' junction='roundabout'`
            - [ ] `roundabout`, `secondary_link`, `hihgway='secondary_link' junction='roundabout'`
            - [ ] `roundabout`, `tertiary`, `hihgway='tertiary' junction='roundabout'`
            - [ ] `roundabout`, `trunk`, `hihgway='trunk' junction='roundabout'`
            - [ ] `roundabout`, `trunk_link`, `hihgway='trunk_link' junction='roundabout'`
            - [ ] `roundabout`, `unclassified`, `hihgway='unclassified' junction='roundabout'`
            - [ ] *aggtpyes*: others, highway_links, major_road, minor_road, no_large_vehicule, roundabout, small_road, track

**Comment by hixi** [comment]
Simplification goal: save about 50% on the output data.

- Leave out the not needed tables
- don't include the buildings table
- only include roads up to level 2 (leaving out level 3-6)

Maybe even simplification of roads.
